version: "3.5"

services:
  data-mesh-demo-airport-api-1:
    image: trivadis/data-mesh-demo-airport-api:latest
    hostname: data-mesh-demo-airport-api-1
    container_name: data-mesh-demo-airport-api-1
    labels:
      com.platys.restapi.title: 'data-mesh-demo-airport-api-1'
      com.platys.restapi.url: "http://${PUBLIC_IP}:48080"
    ports:
      - "48080:8082"

  data-mesh-poc-operations-db-api-1:
    image: trivadis/data-mesh-poc-operations-db-api:latest
    hostname: data-mesh-poc-operations-db-api-1
    container_name: data-mesh-poc-operations-db-api-1
    labels:
      com.platys.restapi.title: 'data-mesh-demo-airport-api-1'
      com.platys.restapi.url: "http://${PUBLIC_IP}:48082"
    ports:
      - "48082:8082"
